// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'box': string;
  'customButton': string;
  'customFooter': string;
  'customFrame': string;
  'customNuv': string;
  'custom_button': string;
  'custom_footer': string;
  'custom_frame': string;
  'custom_nuv': string;
  'description': string;
  'descriptionInner': string;
  'loading': string;
  'loadingBg': string;
  'myBar': string;
  'myProgress': string;
  'result': string;
  'selectionTable': string;
  'selection_table': string;
  'tableFrame': string;
  'table_frame': string;
  'title': string;
  'trButton': string;
  'tr_button': string;
}
declare var cssExports: CssExports;
export = cssExports;
