// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonInHeader': string;
  'button_in_header': string;
  'clearButtonInHeader': string;
  'clear_button_in_header': string;
  'customContent': string;
  'customFrame': string;
  'customHeader': string;
  'customNuv': string;
  'custom_content': string;
  'custom_frame': string;
  'custom_header': string;
  'custom_nuv': string;
  'customloader': string;
  'customloaderParent': string;
  'load5': string;
  'resultTable': string;
  'result_table': string;
  'space': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
